version: '3'
services:
  app:
    build: .
    ports:
      - "9000:9000"
    links:
      - mysql
    environment:
      MYSQL_DATABASE_URL: jdbc:mysql://mysql:3306/school
      MYSQL_USER: school_user
      MYSQL_USER_PASSWORD: pass
  mysql:
    image: mysql:8.0.16
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
      MYSQL_USER: school_user
      MYSQL_USER_PASSWORD: pass

